import type { NextPage } from 'next'
import Head from 'next/head'

type OtherProps = {
  message: ''
}


const Other: NextPage<OtherProps> = ({ message }) => {


  return (
    <div className=''>
      <Head>
        <title>Other - RootLab | NextJS Products (Typescript format)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <h1 className=''>
          Welcome to the RootLab | Rootstack - Other
        </h1>

        <p className=''>
          <code className=''>Typescript</code>
        </p>

      </main>

      <footer className=''>
        <a
          href="https://github.com/jhosebro"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className=''>
            Jhosebro industries
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Other

export async function getServerSideProps() {
  const message = 'Message'
  return {
    props: {
      message
    },
  }
}
