import type { NextPage } from 'next'
import Head from 'next/head'

type BlogProps = {
  posts: string[]
}


const Blog: NextPage<BlogProps> = ({ posts }) => {


  return (
    <div className=''>
      <Head>
        <title>Blog - RootLab | NextJS Products (Typescript format)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <h1 className=''>
          Welcome to the RootLab | Rootstack - Blog
        </h1>

        <p className=''>
          <code className=''>Typescript</code>
        </p>

      </main>

      <footer className=''>
        <a
          href="https://github.com/jhosebro"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className=''>
            Jhosebro industries
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Blog

export async function getServerSideProps() {
  const posts = ['']
  return {
    props: {
      posts
    },
  }
}
