import type { NextPage } from 'next'
import Head from 'next/head'

type HomeProps = {
  response: string
}


const Home: NextPage<HomeProps> = ({ response }) => {


  return (
    <div className=''>
      <Head>
        <title>RootLab | NextJS Products (Typescript format)</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className=''>
        <h1 className=''>
          Welcome to the RootLab | Rootstack
        </h1>

        <p className=''>
          <code className=''>Typescript mode {response}</code>
        </p>

      </main>

      <footer className=''>
        <a
          href="https://github.com/jhosebro"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className=''>
            Jhosebro industries
          </span>
        </a>
      </footer>
    </div>
  )
}

export default Home

export async function getServerSideProps() {
  const response = 'with jhosebro'
  return {
    props: {
      response
    },
  }
}
